#!/bin/sh
rsync -rtLv --delete-after --modify-window=1 --filter=': /.rsync' -e ssh ~/emetric/C/DLLS/ win.vm:/cygdrive/c/DLLS
time rsync $@ -rtLv --delete-after --modify-window=1 --filter=': /.rsync' -e ssh '/Users/bsuh/emetric/C/Users/bsuh/Documents/Visual Studio 2013/Projects/' "win.vm:/cygdrive/c/Users/bsuh/Documents/Visual\ Studio\ 2013/Projects"
